customCommands:
  - key: "R"
    command: "gh pr create --base main --title '{{.SelectedRemoteBranch.Name}}' --fill"
    context: "remoteBranches"
    description: "Create GitHub Pull Request"
    loadingText: "Creating pull request..."
